### ISSUE TITLE
Nethogs or similar integration in NUMA

### ISSUE THREAD

**Issue by matrixik** [pdcurtis/cinnamon-applets#3]
Hello and thank you for NUMA.

Just an idea: maybe it would be possible to integrate NetHogs with NUMA to see what is actually eating most of the transfer?

https://github.com/raboof/nethogs

**Comment by pdcurtis** [comment]
@matrixik 
Thank you for the suggestion of integrate NetHogs with NUMA to see what is actually eating most of the transfers. It would be very nice to have easy access to the information in NetHogs perhaps in the same way as the vnStat screen is integrated into NUMA.

There are a number of problems not least of which is that NetHogs needs root access to run - I have not looked under the hood to see exactly how it works in detail  but I suspect it might need a complete re-write prior to integrate any of the facilities. It is possible to fudge access to programs run as root without needing passwords but they usually end up as a huge security risk.

I do not have the time to look at it further at the moment but I will leave the issue open open in case somebody else wants to have a look into it and push an update or suggest alternative ways to get the same information, perhaps from a small program/daemon permanently running and providing output which NUMA or a new applet could pick up without root access. In fact I think I favour starting with a new applet, and then looking to see if integration would be sensible..
